;;; monokai-sunny-theme.el --- Monokai Sunny Theme

;; Copyright 2017-present, All rights reserved
;;
;; Code licensed under the MIT license

;; Author: vaicine
;; Version: 1.0.0
;; Package-Requires: ((emacs "24"))
;; URL: https://github.com/vaicine/monokai-sunny-theme

;;; Commentary:

;; A lighter version of the popular monokai theme

;;; Code:

(deftheme monokai-sunny)

(custom-theme-set-variables
 'monokai-sunny
 '(ansi-color-names-vector ["#fbf8ef" "#F92672" "#A6E22E" "#E6DB74" "#66D9EF" "#FD5FF0" "#A1EFE4" "#949187"])
 '(compilation-message-face (quote (quote default)))
 '(fci-rule-color "#eeeade"))

(custom-theme-set-faces
 'monokai-sunny
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#AE81FF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :italic nil)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :italic nil))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold :italic t :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(button ((t (:underline t))))
 '(highlight ((((class color) (min-colors 257)) (:background "#c9c6bb")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:inherit highlight :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit highlight :background "#8B8878"))))
 '(region ((((class color) (min-colors 257)) (:inherit highlight :background "#c9c6bb")) (((class color) (min-colors 89)) (:inherit highlight :background "#474747"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:inherit region :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit region :background "#3E3E3E"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(match ((((class color) (min-colors 257)) (:background "#A6E22E" :foreground "#fbf8ef" :weight bold)) (((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :weight bold))))
 '(cursor ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#949187" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#949187" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(fringe ((((class color) (min-colors 257)) (:foreground "#949187" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#AE81FF" :underline t :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :underline t :weight normal))))
 '(success ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(eval-sexp-fu-flash ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#87D700"))))
 '(eval-sexp-fu-flash-error ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#F92672")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#FF1493"))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#F92672")) (((class color) (min-colors 89)) (:background "#FF1493"))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#64645E")) (((class color) (min-colors 89)) (:foreground "#3D3D3D"))))
 '(menu ((((class color) (min-colors 257)) (:foreground "#949187" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mode-line-buffer-id ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(mode-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#F8F8F0" :background "#c9c6bb" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#1B1E1C" :box (:line-width 1 :color "#474747" :style unspecified)))))
 '(powerline-active1 ((((class color) (min-colors 257)) (:background "#35331D")) (((class color) (min-colors 89)) (:background "#333333"))))
 '(powerline-active2 ((((class color) (min-colors 257)) (:background "#fbf8ef")) (((class color) (min-colors 89)) (:background "#1B1E1C"))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#75715E" :background "#fbf8ef" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C" :box (:line-width 1 :color "#3D3D3D" :style unspecified)))))
 '(powerline-inactive1 ((((class color) (min-colors 257)) (:background "#35331D")) (((class color) (min-colors 89)) (:background "#333333"))))
 '(powerline-inactive2 ((((class color) (min-colors 257)) (:background "#fbf8ef")) (((class color) (min-colors 89)) (:background "#1B1E1C"))))
 '(header-line ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#c9c6bb" :box (:color "#64645E" :line-width 1 :style unspecified))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#474747" :box (:color "#3D3D3D" :line-width 1 :style unspecified)))))
 '(diary ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#66D9EF" :background "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 257)) (:inherit shadow)) (((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#AE81FF" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#949187" :underline t)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :slant italic)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :slant italic))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#FD971F" :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(isearch ((((class color) (min-colors 257)) (:inherit region :background "#A6E22E")) (((class color) (min-colors 89)) (:inherit region :background "#87D700"))))
 '(isearch-fail ((((class color) (min-colors 257)) (:inherit isearch :foreground "#F92672" :background "#fbf8ef" :bold t)) (((class color) (min-colors 89)) (:inherit isearch :foreground "#FF1493" :background "#1B1E1C" :bold t))))
 '(ahs-definition-face ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF"))))
 '(ahs-edit-mode-face ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#c9c6bb")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#474747"))))
 '(ahs-face ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#D700D7" :background unspecified))))
 '(ahs-plugin-bod-face ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FFFFF"))))
 '(ahs-plugin-defalt-face ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#FD971F")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#FF8C00"))))
 '(ahs-plugin-whole-buffer-face ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#87D700"))))
 '(ahs-warning-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(anzu-mode-line ((((class color) (min-colors 257)) (:foreground "#AE81FF" :weight bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight bold))))
 '(company-tooltip ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#F8F8F0")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA"))))
 '(company-tooltip-selection ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#fbf8ef")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(company-tooltip-mouse ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#fbf8ef")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(company-tooltip-common ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(company-tooltip-common-selection ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF" :underline t))))
 '(company-preview ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#F8F8F0")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA"))))
 '(company-preview-common ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(company-scrollbar-bg ((((class color) (min-colors 257)) (:background "#64645E")) (((class color) (min-colors 89)) (:background "#3D3D3D"))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#75715E")) (((class color) (min-colors 89)) (:background "#8B8878"))))
 '(company-tooltip-annotation ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#A6E22E")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#87D700"))))
 '(company-template-field ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#66D9EF")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#5FD7FF"))))
 '(compilation-column-number ((((class color) (min-colors 257)) (:inherit font-lock-doc-face :foreground "#A1EFE4" :underline nil)) (((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#5FFFFF" :underline nil))))
 '(compilation-error ((((class color) (min-colors 257)) (:inherit error :underline nil)) (((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 257)) (:foreground "#75715E" :underline nil :bold nil)) (((class color) (min-colors 89)) (:foreground "#8B8878" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#A6E22E" :underline nil)) (((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 257)) (:inherit warning :underline nil)) (((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 257)) (:inherit compilation-info :foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-info :foreground "#87D700" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 257)) (:inherit compilation-error :foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-error :foreground "#FF1493" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(custom-face-tag ((((class color) (min-colors 257)) (:inherit default :height 1.2 :foreground "#AE81FF" :weight bold)) (((class color) (min-colors 89)) (:inherit default :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#A1EFE4" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#66D9EF" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:inherit default :foreground "#F92672" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#FF1493" :height 1.2))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(diff-added ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C"))))
 '(diff-changed ((((class color) (min-colors 257)) (:foreground "#66D9EF" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C"))))
 '(diff-removed ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C"))))
 '(diff-header ((((class color) (min-colors 257)) (:background "#fbf8ef")) (((class color) (min-colors 89)) (:background "#1B1E1C"))))
 '(diff-file-header ((((class color) (min-colors 257)) (:background "#fbf8ef" :foreground "#949187" :weight bold)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5" :weight bold))))
 '(diff-refine-added ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#87D700"))))
 '(diff-refine-changed ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF"))))
 '(diff-refine-removed ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#F92672")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#FF1493"))))
 '(diff-hl-change ((((class color) (min-colors 257)) (:background "#1DB4D0" :foreground "#CAF5FD")) (((class color) (min-colors 89)) (:background "#87D7FF" :foreground "#008787"))))
 '(diff-hl-delete ((((class color) (min-colors 257)) (:background "#F20055" :foreground "#FEB0CC")) (((class color) (min-colors 89)) (:background "#FF5F87" :foreground "#870000"))))
 '(diff-hl-insert ((((class color) (min-colors 257)) (:background "#679A01" :foreground "#CCF47C")) (((class color) (min-colors 89)) (:background "#AFD700" :foreground "#5F8700"))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#FA518D" :inherit italic)) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FF5F87" :inherit italic))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#BBEF53" :inherit italic)) (((class color) (min-colors 89)) (:background "#000000" :foreground "#AFD700" :inherit italic))))
 '(evil-search-highlight-persist-highlight-face ((((class color) (min-colors 257)) (:inherit region)) (((class color) (min-colors 89)) (:inherit region))))
 '(flx-highlight-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal :underline nil))))
 '(git-gutter:added ((((class color) (min-colors 257)) (:background "#A6E22E" :foreground "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :inherit bold))))
 '(git-gutter:deleted ((((class color) (min-colors 257)) (:background "#F92672" :foreground "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :inherit bold))))
 '(git-gutter:modified ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C" :inherit bold))))
 '(git-gutter:unchanged ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:background "#000000" :foreground "#1B1E1C" :inherit bold))))
 '(git-gutter-fr:added ((((class color) (min-colors 257)) (:foreground "#A6E22E" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :inherit bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 257)) (:foreground "#F92672" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :inherit bold))))
 '(git-gutter-fr:modified ((((class color) (min-colors 257)) (:foreground "#66D9EF" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :inherit bold))))
 '(git-gutter+-added ((((class color) (min-colors 257)) (:background "#A6E22E" :foreground "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :inherit bold))))
 '(git-gutter+-deleted ((((class color) (min-colors 257)) (:background "#F92672" :foreground "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :inherit bold))))
 '(git-gutter+-modified ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C" :inherit bold))))
 '(git-gutter+-unchanged ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#fbf8ef" :inherit bold)) (((class color) (min-colors 89)) (:background "#000000" :foreground "#1B1E1C" :inherit bold))))
 '(git-gutter-fr+-added ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(git-gutter-fr+-deleted ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(git-gutter-fr+-modified ((((class color) (min-colors 257)) (:foreground "#66D9EF" :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(helm-bookmark-directory ((((class color) (min-colors 257)) (:inherit helm-ff-directory)) (((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 257)) (:foreground "#949187")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(helm-bookmark-info ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-bookmark-man ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(helm-buffer-file ((((class color) (min-colors 257)) (:foreground "#949187")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-buffer-directory ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(helm-buffer-process ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#fbf8ef" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :inverse-video t))))
 '(helm-buffer-size ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(helm-candidate-number ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#F8F8F0" :bold t)) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA" :bold t))))
 '(helm-ff-directory ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(helm-ff-executable ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-ff-file ((((class color) (min-colors 257)) (:background "#fbf8ef" :foreground "#949187")) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 257)) (:background "#fbf8ef" :foreground "#FD971F" :slant italic)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#FF8C00" :slant italic))))
 '(helm-ff-prefix ((((class color) (min-colors 257)) (:background "#A6E22E" :foreground "#fbf8ef")) (((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C"))))
 '(helm-ff-symlink ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(helm-grep-file ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline t))))
 '(helm-grep-finish ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-grep-lineno ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(helm-grep-match ((((class color) (min-colors 257)) (:inherit helm-match))))
 '(helm-header ((((class color) (min-colors 257)) (:inherit header-line)) (((class color) (min-colors 89)) (:inherit terminal-header-line))))
 '(helm-lisp-completion-info ((((class color) (min-colors 257)) (:foreground "#949187")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-lisp-show-completion ((((class color) (min-colors 257)) (:foreground "#E6DB74" :background "#eeeade" :bold t)) (((class color) (min-colors 89)) (:foreground "#CDC673" :background "#000000" :bold t))))
 '(helm-M-x-key ((((class color) (min-colors 257)) (:foreground "#FD971F" :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(helm-moccur-buffer ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline t))))
 '(helm-match ((((class color) (min-colors 257)) (:foreground "#A6E22E" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :inherit bold))))
 '(helm-match-item ((((class color) (min-colors 257)) (:inherit helm-match)) (((class color) (min-colors 89)) (:inherit helm-match))))
 '(helm-selection ((((class color) (min-colors 257)) (:background "#c9c6bb" :inherit bold :underline nil)) (((class color) (min-colors 89)) (:background "#474747" :inherit bold :underline nil))))
 '(helm-selection-line ((((class color) (min-colors 257)) (:background "#eeeade" :foreground "#F8F8F0" :underline nil)) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA" :underline nil))))
 '(helm-separator ((((class color) (min-colors 257)) (:foreground "#64645E")) (((class color) (min-colors 89)) (:foreground "#3D3D3D"))))
 '(helm-source-header ((((class color) (min-colors 257)) (:background "#C9ACFF" :foreground "#fbf8ef" :underline nil)) (((class color) (min-colors 89)) (:background "#AF87D7" :foreground "#1B1E1C" :underline nil))))
 '(helm-visible-mark ((((class color) (min-colors 257)) (:background "#fbf8ef" :foreground "#FD5FF0" :bold t)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#D700D7" :bold t))))
 '(hl-line ((((class color) (min-colors 257)) (:background "#eeeade")) (((class color) (min-colors 89)) (:background "#000000"))))
 '(ido-first-match ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 257)) (:foreground "#fbf8ef" :background "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 257)) (:background "#F92672" :foreground "#fbf8ef" :width condensed)) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(info-header-xref ((((class color) (min-colors 257)) (:foreground "#A6E22E" :inherit bold :underline t)) (((class color) (min-colors 89)) (:foreground "#87D700" :inherit bold :underline t))))
 '(info-menu ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(info-node ((((class color) (min-colors 257)) (:foreground "#AE81FF" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :inherit bold))))
 '(info-quoted-name ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(info-reference-item ((((class color) (min-colors 257)) (:background nil :underline t :inherit bold)) (((class color) (min-colors 89)) (:background nil :underline t :inherit bold))))
 '(info-string ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(info-title-1 ((((class color) (min-colors 257)) (:height 1.3)) (((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-2 ((((class color) (min-colors 257)) (:height 1.2)) (((class color) (min-colors 89)) (:height 1.2))))
 '(info-title-3 ((((class color) (min-colors 257)) (:height 1.15)) (((class color) (min-colors 89)) (:height 1.15))))
 '(info-title-4 ((((class color) (min-colors 257)) (:height 1.1)) (((class color) (min-colors 89)) (:height 1.1))))
 '(linum ((((class color) (min-colors 257)) (:foreground "#8F908A" :background "#fbf8ef" :underline nil)) (((class color) (min-colors 89)) (:foreground "#8F908A" :background "#1B1E1C" :underline nil))))
 '(magit-diff-added ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C"))))
 '(magit-diff-added-highlight ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#eeeade")) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#000000"))))
 '(magit-diff-removed ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C"))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#eeeade")) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#000000"))))
 '(magit-log-author ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(magit-log-graph ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-cited-text ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-header-name ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-header-other ((((class color) (min-colors 257)) (:foreground "#949187" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-to ((((class color) (min-colors 257)) (:foreground "#949187" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 257)) (:foreground "#949187" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(message-mml ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-separator ((((class color) (min-colors 257)) (:foreground "#75715E" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-agenda-structure ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#eeeade" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#fbf8ef"))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#000000" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 257)) (:foreground "#F8F8F0")) (((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 257)) (:foreground "#949187" :slant italic)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#fbf8ef" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#fbf8ef"))) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-date-weekend ((((class color) (min-colors 257)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#75715E" :weight unspecified :underline t :overline nil :box unspecified)) (((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#8B8878" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 257)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#66D9EF" :background "#fbf8ef")) (((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#5FD7FF" :background "#1B1E1C"))))
 '(org-agenda-done ((((class color) (min-colors 257)) (:foreground "#75715E" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-archived ((((class color) (min-colors 257)) (:foreground "#75715E" :weight normal)) (((class color) (min-colors 89)) (:foreground "#8B8878" :weight normal))))
 '(org-block ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#3E3D31")) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#3E3E3E"))))
 '(org-block-begin-line ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#35331D" :slant italic)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#333333" :slant italic))))
 '(org-block-end-line ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#35331D" :slant italic)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#333333" :slant italic))))
 '(org-checkbox ((((class color) (min-colors 257)) (:background "#fbf8ef" :foreground "#949187" :box (:line-width 1 :style released-button))) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-date ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(org-done ((((class color) (min-colors 257)) (:weight bold :foreground "#A6E22E")) (((class color) (min-colors 89)) (:weight bold :foreground "#87D700"))))
 '(org-ellipsis ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-formula ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(org-headline-done ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-hide ((((class color) (min-colors 257)) (:foreground "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#1B1E1C"))))
 '(org-level-1 ((((class color) (min-colors 257)) (:inherit default :height 1.3 :foreground "#FD971F")) (((class color) (min-colors 89)) (:inherit default :height 1.3 :foreground "#FF8C00"))))
 '(org-level-2 ((((class color) (min-colors 257)) (:inherit default :height 1.2 :foreground "#A6E22E")) (((class color) (min-colors 89)) (:inherit default :height 1.2 :foreground "#87D700"))))
 '(org-level-3 ((((class color) (min-colors 257)) (:inherit default :height 1.15 :foreground "#66D9EF")) (((class color) (min-colors 89)) (:inherit default :height 1.15 :foreground "#5FD7FF"))))
 '(org-level-4 ((((class color) (min-colors 257)) (:inherit default :height 1.1 :foreground "#E6DB74")) (((class color) (min-colors 89)) (:inherit default :height 1.1 :foreground "#CDC673"))))
 '(org-level-5 ((((class color) (min-colors 257)) (:inherit default :foreground "#A1EFE4")) (((class color) (min-colors 89)) (:inherit default :foreground "#5FFFFF"))))
 '(org-level-6 ((((class color) (min-colors 257)) (:inherit default :foreground "#A6E22E")) (((class color) (min-colors 89)) (:inherit default :foreground "#87D700"))))
 '(org-level-7 ((((class color) (min-colors 257)) (:inherit default :foreground "#F92672")) (((class color) (min-colors 89)) (:inherit default :foreground "#FF1493"))))
 '(org-level-8 ((((class color) (min-colors 257)) (:inherit default :foreground "#66D9EF")) (((class color) (min-colors 89)) (:inherit default :foreground "#5FD7FF"))))
 '(org-link ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(org-sexp-date ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(org-scheduled ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-scheduled-previously ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-scheduled-today ((((class color) (min-colors 257)) (:foreground "#66D9EF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 257)) (:foreground "#75715E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#8B8878" :weight bold))))
 '(org-table ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-tag ((((class color) (min-colors 257)) (:weight bold)) (((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-todo ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight normal :underline nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 257)) (:background "#E6DB74")) (((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-clock-overlay ((((class color) (min-colors 257)) (:background "#E6DB74")) (((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-column ((((class color) (min-colors 257)) (:background "#eeeade" :strike-through nil :underline nil :slant normal :weight normal :inherit default)) (((class color) (min-colors 89)) (:background "#000000" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 257)) (:background "#eeeade" :underline t :weight bold)) (((class color) (min-colors 89)) (:background "#000000" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 257)) (:foreground "#F92672" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 257)) (:foreground "#949187")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(org-document-title ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :weight bold :height 1.3)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-footnote ((((class color) (min-colors 257)) (:foreground "#FD5FF0" :underline t)) (((class color) (min-colors 89)) (:foreground "#D700D7" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 257)) (:inherit mode-line)) (((class color) (min-colors 89)) (:inherit mode-line))))
 '(outline-1 ((((class color) (min-colors 257)) (:inherit org-level-1)) (((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 257)) (:inherit org-level-2)) (((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 257)) (:inherit org-level-3)) (((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 257)) (:inherit org-level-4)) (((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 257)) (:inherit org-level-5)) (((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 257)) (:inherit org-level-6)) (((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 257)) (:inherit org-level-7)) (((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 257)) (:inherit org-level-8)) (((class color) (min-colors 89)) (:inherit org-level-8))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 257)) (:foreground "#949187" :background "#fbf8ef" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C" :inverse-video t))))
 '(sp-pair-overlay-face ((((class color) (min-colors 257)) (:background "#eeeade")) (((class color) (min-colors 89)) (:background "#000000"))))
 '(sp-wrap-overlay-face ((((class color) (min-colors 257)) (:background "#eeeade")) (((class color) (min-colors 89)) (:background "#000000"))))
 '(sp-wrap-tag-overlay-face ((((class color) (min-colors 257)) (:background "#eeeade")) (((class color) (min-colors 89)) (:background "#000000"))))
 '(sp-show-pair-enclosing ((((class color) (min-colors 257)) (:inherit highlight)) (((class color) (min-colors 89)) (:inherit highlight))))
 '(sp-show-pair-match-face ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#fbf8ef" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#fbf8ef" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-match ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#fbf8ef" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#fbf8ef" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#BBEF53" :foreground "#fbf8ef" :inherit default))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C"))))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :inverse-video t))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#fbf8ef" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C" :weight bold))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(vhl/default-face ((((class color) (min-colors 257)) (:background "#679A01" :foreground "#CCF47C")) (((class color) (min-colors 89)) (:background "#AFD700" :foreground "#5F8700"))))
 '(which-key-key-face ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(which-key-separator-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(which-key-note-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(which-key-command-description-face ((((class color) (min-colors 257)) (:foreground "#949187")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(which-key-local-map-description-face ((((class color) (min-colors 257)) (:foreground "#FFFACE")) (((class color) (min-colors 89)) (:foreground "#878700"))))
 '(which-key-group-description-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(default ((((class color) (min-colors 257)) (:foreground "#949187" :background "#fbf8ef")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C")))))

(provide-theme 'monokai-sunny)
